version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: evdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ev_marketplace
      MYSQL_USER: ev_user
      MYSQL_PASSWORD: ev_pass
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
